// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.1
//   protoc               unknown
// source: booking-service_grpc_booking.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";

export const protobufPackage = "coolcinema.booking.rpc";

export interface GetBookingRequest {
  id: string;
}

export interface GetBookingResponse {
  id: string;
  email: string;
  isActive: boolean;
}

function createBaseGetBookingRequest(): GetBookingRequest {
  return { id: "" };
}

export const GetBookingRequest: MessageFns<GetBookingRequest> = {
  encode(message: GetBookingRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBookingRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBookingRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetBookingRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: GetBookingRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create(base?: DeepPartial<GetBookingRequest>): GetBookingRequest {
    return GetBookingRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetBookingRequest>): GetBookingRequest {
    const message = createBaseGetBookingRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseGetBookingResponse(): GetBookingResponse {
  return { id: "", email: "", isActive: false };
}

export const GetBookingResponse: MessageFns<GetBookingResponse> = {
  encode(message: GetBookingResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.email !== "") {
      writer.uint32(18).string(message.email);
    }
    if (message.isActive !== false) {
      writer.uint32(24).bool(message.isActive);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBookingResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBookingResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.isActive = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetBookingResponse {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      isActive: isSet(object.isActive)
        ? globalThis.Boolean(object.isActive)
        : isSet(object.is_active)
        ? globalThis.Boolean(object.is_active)
        : false,
    };
  },

  toJSON(message: GetBookingResponse): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.isActive !== false) {
      obj.isActive = message.isActive;
    }
    return obj;
  },

  create(base?: DeepPartial<GetBookingResponse>): GetBookingResponse {
    return GetBookingResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetBookingResponse>): GetBookingResponse {
    const message = createBaseGetBookingResponse();
    message.id = object.id ?? "";
    message.email = object.email ?? "";
    message.isActive = object.isActive ?? false;
    return message;
  },
};

export type BookingServiceDefinition = typeof BookingServiceDefinition;
export const BookingServiceDefinition = {
  name: "BookingService",
  fullName: "coolcinema.booking.rpc.BookingService",
  methods: {
    getUser: {
      name: "GetUser",
      requestType: GetBookingRequest,
      requestStream: false,
      responseType: GetBookingResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface BookingServiceImplementation<CallContextExt = {}> {
  getUser(request: GetBookingRequest, context: CallContext & CallContextExt): Promise<DeepPartial<GetBookingResponse>>;
}

export interface BookingServiceClient<CallOptionsExt = {}> {
  getUser(request: DeepPartial<GetBookingRequest>, options?: CallOptions & CallOptionsExt): Promise<GetBookingResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
