// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.1
//   protoc               unknown
// source: gateway-service_http_main.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";

export const protobufPackage = "coolcinema.gateway.http";

export interface BuyTicketRequest {
  userId: string;
  showtimeId: string;
}

export interface BuyTicketResponse {
  success: boolean;
  ticketId: string;
  price: number;
}

function createBaseBuyTicketRequest(): BuyTicketRequest {
  return { userId: "", showtimeId: "" };
}

export const BuyTicketRequest: MessageFns<BuyTicketRequest> = {
  encode(message: BuyTicketRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.showtimeId !== "") {
      writer.uint32(18).string(message.showtimeId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BuyTicketRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBuyTicketRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.showtimeId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BuyTicketRequest {
    return {
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      showtimeId: isSet(object.showtimeId)
        ? globalThis.String(object.showtimeId)
        : isSet(object.showtime_id)
        ? globalThis.String(object.showtime_id)
        : "",
    };
  },

  toJSON(message: BuyTicketRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.showtimeId !== "") {
      obj.showtimeId = message.showtimeId;
    }
    return obj;
  },

  create(base?: DeepPartial<BuyTicketRequest>): BuyTicketRequest {
    return BuyTicketRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<BuyTicketRequest>): BuyTicketRequest {
    const message = createBaseBuyTicketRequest();
    message.userId = object.userId ?? "";
    message.showtimeId = object.showtimeId ?? "";
    return message;
  },
};

function createBaseBuyTicketResponse(): BuyTicketResponse {
  return { success: false, ticketId: "", price: 0 };
}

export const BuyTicketResponse: MessageFns<BuyTicketResponse> = {
  encode(message: BuyTicketResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.ticketId !== "") {
      writer.uint32(18).string(message.ticketId);
    }
    if (message.price !== 0) {
      writer.uint32(25).double(message.price);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BuyTicketResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBuyTicketResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ticketId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.price = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BuyTicketResponse {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      ticketId: isSet(object.ticketId)
        ? globalThis.String(object.ticketId)
        : isSet(object.ticket_id)
        ? globalThis.String(object.ticket_id)
        : "",
      price: isSet(object.price) ? globalThis.Number(object.price) : 0,
    };
  },

  toJSON(message: BuyTicketResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.ticketId !== "") {
      obj.ticketId = message.ticketId;
    }
    if (message.price !== 0) {
      obj.price = message.price;
    }
    return obj;
  },

  create(base?: DeepPartial<BuyTicketResponse>): BuyTicketResponse {
    return BuyTicketResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<BuyTicketResponse>): BuyTicketResponse {
    const message = createBaseBuyTicketResponse();
    message.success = object.success ?? false;
    message.ticketId = object.ticketId ?? "";
    message.price = object.price ?? 0;
    return message;
  },
};

export type GatewayApiDefinition = typeof GatewayApiDefinition;
export const GatewayApiDefinition = {
  name: "GatewayApi",
  fullName: "coolcinema.gateway.http.GatewayApi",
  methods: {
    /** POST /buy-ticket */
    buyTicket: {
      name: "BuyTicket",
      requestType: BuyTicketRequest,
      requestStream: false,
      responseType: BuyTicketResponse,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([19, 58, 1, 42, 34, 14, 47, 118, 49, 47, 98, 117, 121, 45, 116, 105, 99, 107, 101, 116]),
          ],
        },
      },
    },
  },
} as const;

export interface GatewayApiServiceImplementation<CallContextExt = {}> {
  /** POST /buy-ticket */
  buyTicket(request: BuyTicketRequest, context: CallContext & CallContextExt): Promise<DeepPartial<BuyTicketResponse>>;
}

export interface GatewayApiClient<CallOptionsExt = {}> {
  /** POST /buy-ticket */
  buyTicket(request: DeepPartial<BuyTicketRequest>, options?: CallOptions & CallOptionsExt): Promise<BuyTicketResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
