// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.1
//   protoc               unknown
// source: sales-service_grpc_sales.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";

export const protobufPackage = "coolcinema.sales.rpc";

export interface CalculatePriceRequest {
  showtimeId: string;
}

export interface CalculatePriceResponse {
  amount: number;
  currency: string;
}

function createBaseCalculatePriceRequest(): CalculatePriceRequest {
  return { showtimeId: "" };
}

export const CalculatePriceRequest: MessageFns<CalculatePriceRequest> = {
  encode(message: CalculatePriceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.showtimeId !== "") {
      writer.uint32(10).string(message.showtimeId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CalculatePriceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCalculatePriceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.showtimeId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CalculatePriceRequest {
    return {
      showtimeId: isSet(object.showtimeId)
        ? globalThis.String(object.showtimeId)
        : isSet(object.showtime_id)
        ? globalThis.String(object.showtime_id)
        : "",
    };
  },

  toJSON(message: CalculatePriceRequest): unknown {
    const obj: any = {};
    if (message.showtimeId !== "") {
      obj.showtimeId = message.showtimeId;
    }
    return obj;
  },

  create(base?: DeepPartial<CalculatePriceRequest>): CalculatePriceRequest {
    return CalculatePriceRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CalculatePriceRequest>): CalculatePriceRequest {
    const message = createBaseCalculatePriceRequest();
    message.showtimeId = object.showtimeId ?? "";
    return message;
  },
};

function createBaseCalculatePriceResponse(): CalculatePriceResponse {
  return { amount: 0, currency: "" };
}

export const CalculatePriceResponse: MessageFns<CalculatePriceResponse> = {
  encode(message: CalculatePriceResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.amount !== 0) {
      writer.uint32(9).double(message.amount);
    }
    if (message.currency !== "") {
      writer.uint32(18).string(message.currency);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CalculatePriceResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCalculatePriceResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.amount = reader.double();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.currency = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CalculatePriceResponse {
    return {
      amount: isSet(object.amount) ? globalThis.Number(object.amount) : 0,
      currency: isSet(object.currency) ? globalThis.String(object.currency) : "",
    };
  },

  toJSON(message: CalculatePriceResponse): unknown {
    const obj: any = {};
    if (message.amount !== 0) {
      obj.amount = message.amount;
    }
    if (message.currency !== "") {
      obj.currency = message.currency;
    }
    return obj;
  },

  create(base?: DeepPartial<CalculatePriceResponse>): CalculatePriceResponse {
    return CalculatePriceResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CalculatePriceResponse>): CalculatePriceResponse {
    const message = createBaseCalculatePriceResponse();
    message.amount = object.amount ?? 0;
    message.currency = object.currency ?? "";
    return message;
  },
};

export type SalesServiceDefinition = typeof SalesServiceDefinition;
export const SalesServiceDefinition = {
  name: "SalesService",
  fullName: "coolcinema.sales.rpc.SalesService",
  methods: {
    calculatePrice: {
      name: "CalculatePrice",
      requestType: CalculatePriceRequest,
      requestStream: false,
      responseType: CalculatePriceResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface SalesServiceImplementation<CallContextExt = {}> {
  calculatePrice(
    request: CalculatePriceRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<CalculatePriceResponse>>;
}

export interface SalesServiceClient<CallOptionsExt = {}> {
  calculatePrice(
    request: DeepPartial<CalculatePriceRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<CalculatePriceResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
